#!/usr/bin/env python

from __future__ import print_function

import os
import shutil
import tempfile
import subprocess
import glob

from scan_pdf import Scanner, Converter, Combiner

output_file_name = "combined.pdf"

olddir = os.getcwd()
dir = tempfile.mkdtemp(suffix='_scanpdf')
os.chdir(dir)

print("tmp dir:", dir)

options = object()
options.resolution = 300
options.color_mode = 'gray'
options.color_depth = 4
options.paper_format = 'A4'
options.output_file_name = 'combined.pdf'

scanner = Scanner(options)

subprocess.call(['ls', '-la'])

output_basenames = scanner.get_page_file_basenames()

converter = Converter(options)
for output_basename in output_basenames:
    converter.convert(output_basename, scanner.page_file_suffix)

subprocess.call(['ls', '-la'])

combiner = Combiner(options)
combiner.combine([output_basename + converter.page_file_suffix for output_basename in output_basenames])

subprocess.call(['ls', '-la'])

os.chdir(olddir)
shutil.move(os.path.join(dir, os.path.basename(output_file_name)), output_file_name)

shutil.rmtree(dir, ignore_errors=True)
